env:
  cron: ''
  discord_notifications: ''
  discord_url: ''
  mastercontconcheck: ''
  mastercontname: ''
  ping_count: ''
  ping_ip: ''
  ping_ip_alt: ''
  run_startup: ''
  sleep_secs: ''
image:
  pullPolicy: IfNotPresent
  repository: eafxx/rebuild-dndc
  tag: unraid-m
persistence:
  config:
    enabled: true
    mountPath: /config/rebuild-dndc
  dockersock:
    enabled: true
    mountPath: /var/run/docker.sock
  dockertemplatelocation:
    enabled: true
    mountPath: /config/docker-templates
    readOnly: true
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
