CategoryList:
- HomeAutomation
Config:
  Device: {}
  Label: {}
  Path:
    config:
      Default: /mnt/user/appdata/home-assistant-configurator/
      Description: 'Container Path: /config'
      Display: always
      Mask: 'false'
      Mode: rw
      Name: config
      Required: 'true'
      Target: /config
      Type: Path
      value: ''
    hass-config:
      Default: /mnt/user/appdata/home-assistant/
      Description: "Your home assistant configuration folder\r\n"
      Display: always
      Mask: 'false'
      Mode: rw
      Name: hass-config
      Required: 'false'
      Target: /hass-config
      Type: Path
      value: ''
  Port:
    main:
      Default: '3218'
      Description: 'Container Port: 3218'
      Display: always
      Mask: 'false'
      Mode: tcp
      Name: '3218'
      Required: 'false'
      Target: 3218
      Type: Port
      value: 3218
  Variable: {}
Icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/2000px-Home_Assistant_Logo.svg.png
Keywords:
- hassconfigurator
- HomeAutomation
Name: hassconfigurator
Overview: Home Assistant online configurator container from https://github.com/danielperna84/hass-configurator
PostArgs: ''
Privileged: 'false'
Registry: https://hub.docker.com/r/causticlab/hass-configurator-docker//Dockerfile/
Repository: causticlab/hass-configurator-docker
Requires: ''
Sources:
- https://github.com/danielperna84/hass-configurator
- https://hub.docker.com/r/causticlab/hass-configurator-docker//Dockerfile/
Tag: x86_64
WebUI: http://[IP]:[PORT:3218]
